pub mod by_stmt;
pub mod claim_stmt;
pub mod define_algorithm_stmt;
pub mod definition_stmt;
pub mod eval_stmt;
pub mod know_stmt;
pub mod parameter_def;
pub mod prove_stmt;
pub mod tooling_stmt;
pub mod witness_stmt;

mod stmt;
mod stmt_type_name;
pub use stmt::ByClosedRangeAsCasesStmt;
pub use stmt::ByEnumerateRangeStmt;
pub use stmt::ByThmStmt;
pub use stmt::DefStrategyStmt;
pub use stmt::DefStructStmt;
pub use stmt::DefThmStmt;
pub use stmt::EvalByStmt;
pub use stmt::Stmt;
pub use stmt::StopStrategyStmt;
pub use stmt::UseStrategyStmt;
