pub mod known_forall_profile;
mod not_exist_demorgan_forall;
mod verify_and_chain_fact;
mod verify_atomic_fact;
mod verify_atomic_fact_by_definition;
mod verify_atomic_fact_with_known_forall;
mod verify_atomic_fact_with_strategy;
mod verify_builtin_rules;
mod verify_by_syntax;
mod verify_equality;
mod verify_equality_by_builtin_rules;
mod verify_exist_fact;
mod verify_exist_fact_with_known_forall;
mod verify_fact;
mod verify_fact_well_defined;
mod verify_facts_the_same_type_and_return_matched_args;
mod verify_fn_equal_in_builtin;
mod verify_fn_set_equality_builtin_rule;
mod verify_forall_fact;
mod verify_forall_fact_with_iff;
mod verify_helper;
mod verify_known_atomic_facts;
mod verify_non_equational_atomic_fact;
mod verify_not_forall_fact;
pub use verify_builtin_rules::{compare_normalized_number_str_to_zero, NumberCompareResult};
mod verify_arg_satisfy_param_def;
mod verify_number_in_standard_set;
mod verify_obj_well_defined;
mod verify_or_fact;
mod verify_or_fact_with_known_forall;
mod verify_restrict_by_def;
mod verify_state;
mod verify_well_defined_in_local_env;

pub use verify_number_in_standard_set::number_is_in_n;
pub use verify_number_in_standard_set::number_is_in_n_pos;
pub use verify_number_in_standard_set::number_is_in_q_neg;
pub use verify_number_in_standard_set::number_is_in_q_nz;
pub use verify_number_in_standard_set::number_is_in_q_pos;
pub use verify_number_in_standard_set::number_is_in_r_neg;
pub use verify_number_in_standard_set::number_is_in_r_nz;
pub use verify_number_in_standard_set::number_is_in_r_pos;
pub use verify_number_in_standard_set::number_is_in_z;
pub use verify_number_in_standard_set::number_is_in_z_neg;
pub use verify_number_in_standard_set::number_is_in_z_nz;

pub use verify_state::VerifyState;
